apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  template:
    spec:
      containers:
        - name: webhook
          command:
          - "python"
          args:
          - "-m"
          - "ptvsd"
          - "--port"
          - "3000"
          - "--host"
          - "0.0.0.0"
          - "api.py"
