apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patches:
- path: dev-patch.yaml
# - path: metrics-pusher-patch.yaml

resources:
- reader-deployment.yaml
- sensors-amcrest.yaml
- ../bases

commonLabels:
  env: dev
images:
- name: ghcr.io/davidasnider/cava/amcrest-motion
  newTag: v1.0.24
- name: ghcr.io/davidasnider/cava/reader
  newTag: v1.0.24
- name: ghcr.io/davidasnider/cava/webhook
  newTag: v1.0.24
