apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: dev-patch.yaml

resources:
- reader-deployment.yaml
- sensors-amcrest.yaml
- ../bases

commonLabels:
  env: dev
images:
- name: ghcr.io/davidasnider/cava/amcrest-motion
  newTag: v1.0.197
- name: ghcr.io/davidasnider/cava/correlator
  newTag: v1.0.197
- name: ghcr.io/davidasnider/cava/primary
  newTag: v1.0.197
- name: ghcr.io/davidasnider/cava/reader
  newTag: v1.0.197
- name: ghcr.io/davidasnider/cava/runner
  newTag: v1.0.197
