apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../bases

patches:
- path: dev-patch.yaml
# - path: metrics-pusher-patch.yaml

resources:
- reader-deployment.yaml
- sensors-amcrest.yaml

commonLabels:
  env: dev
