[tool.poetry]
name = "cava"
version = "0.1.0"
description = ""
authors = ["David Snider <david@davidsnider.org>"]

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0"
pika = "^1.3.0"
fastapi = "^0.79.0"
statsd = "^3.3.0"
arrow = "^1.1.1"
rule-engine = "^3.5.0"

requests = "^2.28.1"
amcrest = "^1.8.0"
httpx = "0.23.0"
uvicorn = "^0.18.2"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
bandit = "^1.7.0"
black = "^22.6"
flake8 = "^5.0.3"
python-dotenv = "^0.19.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
