[tool.poetry]
name = "cava"
version = "0.1.0"
description = ""
authors = ["David Snider <david@davidsnider.org>"]

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0"
pika = "^1.3.1"
fastapi = "^0.87.0"
statsd = "^4.0.1"
arrow = "^1.2.3"
rule-engine = "^3.5.0"

requests = "^2.28.1"
amcrest = "^1.8.0"
httpx = "0.23.1"
uvicorn = "^0.20.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
bandit = "^1.7.0"
black = "^23.1"
flake8 = "^6.0.0"
python-dotenv = "^0.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
