[tool.poetry]
name = "cava"
version = "0.1.0"
description = ""
authors = ["David Snider <david@davidsnider.org>"]

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0"
pika = "^1.3.1"
fastapi = "^0.110.0"
statsd = "^4.0.1"
arrow = "^1.2.3"
rule-engine = "^4.3.1"

requests = "^2.28.1"
amcrest = "^1.8.0"
httpx = "0.27.0"
uvicorn = "^0.29.0"
pydantic-settings = "^2.2.1"

[tool.poetry.dev-dependencies]
pytest = "^8.1.1"
bandit = "^1.7.8"
black = "^24.2"
flake8 = "^7.0.0"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.6.2"
poetry-plugin-export = "^1.7.0"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
