@startuml

node "Sensors" {
    [Weather Emmitter]
    [Motion Emmitter]
}

node "Webhook" {
    [ Listener 1]
}

database "RabbitMQ Message Exchange" as exchange {
    [Message Exchange]
    [Correlation Queue]
    [Action Queue]
}

node "Processors" {
    [Correlation Processor]
}

node "Executors" {
    [Indigo Executor]
    ' [Metrics Publisher]
}

HTTP --> Webhook : Any HTTP call
[Weather Emmitter] --> Webhook: Http json
[Motion Emmitter] --> Webhook: http json
Webhook --> [Message Exchange]: incoming.motion topic
Webhook --> [Message Exchange]: incoming.weather topic
[Message Exchange] --> [Correlation Queue]: incoming.* topics
[Message Exchange] --> [Action Queue]: action.* topics
[Correlation Processor] <--> [Correlation Queue]: reads all topics
[Correlation Processor] --> [Message Exchange]: indigo.* related actions
[Indigo Executor] <--> [Action Queue]: indigo.* related actions

@enduml
