apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: cava
build:
  artifacts:
    - image: registry.thesniderpad.com/cava-webhook
      context: src/webhook
    - image: registry.thesniderpad.com/cava-reader
      context: src/reader
    - image: registry.thesniderpad.com/cava-sensor
      context: src/sensors
  tagPolicy:
    gitCommit: {}
deploy:
  kustomize:
    paths:
    - ./k8s/dev
profiles:
  - name: dev
    activation:
      - kubeContext: minikube
        command: dev
    build:
      artifacts:
        - image: registry.thesniderpad.com/cava-webhook
          context: src/webhook
        - image: registry.thesniderpad.com/cava-reader
          context: src/reader
        - image: registry.thesniderpad.com/cava-sensor
          context: src/sensors
      tagPolicy:
        dateTime: {}
    deploy:
      kustomize:
        paths:
        - ./k8s/dev
      statusCheckDeadlineSeconds: 600
      kubeContext: minikube
  - name: prod
    activation:
      - kubeContext: k8s2
        command: run
    build:
      artifacts:
        - image: registry.thesniderpad.com/cava-webhook
          context: src/webhook
          custom:
            buildCommand: ./build.sh
        - image: registry.thesniderpad.com/cava-sensor
          context: src/sensors
          custom:
            buildCommand: ./build.sh
      tagPolicy:
        dateTime: {}
    deploy:
      kustomize:
        paths:
        - ./k8s/prod
      statusCheckDeadlineSeconds: 600
