apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../bases

commonLabels:
  env: prod

resources:
- namespace.yaml
- sensors-amcrest.yaml

namespace: cava

patches:
- path: prod-patch.yaml
- path: loadbalancer-patch.yaml
