apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: prod

resources:
- namespace.yaml
- sensors-amcrest.yaml
- ../bases
- sensors-tomorrow-io.yaml

namespace: cava

patches:
- path: prod-patch.yaml
- path: loadbalancer-patch.yaml
- path: loadbalancer-patch-rabbitmq.yaml
images:
- name: ghcr.io/davidasnider/cava/primary
  newTag: v1.0.307
