apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


commonLabels:
  env: prod

resources:
- namespace.yaml
- sensors-amcrest.yaml
- ../bases
- sensors-climacell.yaml

namespace: cava

patches:
- path: prod-patch.yaml
- path: loadbalancer-patch.yaml
images:
- name: ghcr.io/davidasnider/cava/amcrest-motion
  newTag: v1.0.19
- name: ghcr.io/davidasnider/cava/climacell
  newTag: v1.0.19
- name: ghcr.io/davidasnider/cava/reader
  newTag: v1.0.19
- name: ghcr.io/davidasnider/cava/webhook
  newTag: v1.0.19
