apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: webhook
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: webhook
      nodeSelector:
        kubernetes.io/arch: arm
