apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-tomorrow-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-tomorrow-io
  template:
    metadata:
      labels:
        app: sensor-tomorrow-io
    spec:
      containers:
      - name: sensor-tomorrow-io
        image: ghcr.io/davidasnider/cava:latest
        envFrom:
        - secretRef:
            name: cava-passwords
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        imagePullPolicy: IfNotPresent
