apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rabbitmq-deployment.yaml
- rabbitmq-service.yaml
- webhook-deployment.yaml
- webhook-service.yaml
# - metrics-pusher-deployment.yaml
- secrets.yaml
