apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/davidasnider/cava
  newTag: v1.0.171
resources:
- rabbitmq-deployment.yaml
- rabbitmq-service.yaml
- webhook-deployment.yaml
- webhook-service.yaml
- correlator-deployment.yaml
- runner-deployment.yaml
- secrets.yaml
