apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  annotations:
    metallb.universe.tf/allow-shared-ip: cava
spec:
  ports:
  - port: 5672
    name: queue
  - port: 15672
    name: manage
  selector:
    app: rabbitmq
  type: LoadBalancer
