apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      initContainers:
      - name: init-webhook-server
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -zv -w 1 rabbitmq-service 5672; do echo waiting for rabbitmq-service; sleep 2; done;']
      containers:
      - name: webhook
        image: ghcr.io/davidasnider/cava:latest
        command: [
          "uvicorn",
          "--host",
          "0.0.0.0",
          "cava.webhook.main:app",
          "--log-config",
          "/app/cava/logger_config.yaml"
        ]
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "cava"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: cava-passwords
              key: CAVA_PASS
        - name: TOMORROW_IO_API_KEY
          valueFrom:
            secretKeyRef:
              key: TOMORROW_IO_API_KEY
              name: cava-passwords
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
            - "true"
          initialDelaySeconds: 5
          periodSeconds: 5
