apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  annotations:
    metallb.universe.tf/allow-shared-ip: cava
spec:
  selector:
    app: webhook
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
